language: ruby
deploy:
  - heroku
rvm:
  - 2.3.1
services:
  - postgresql
env:
  global:
    - DISPLAY=:99.0
before_script:
  - bundle exec rake db:setup
  - bundle exec rake assets:precompile
  - sleep 5
script:
  - bundle install
  - bundle exec rake --trace
cache: bundler
after_success:
  - coveralls
